### PR TITLE
Adding call to fire OnCrewmemberHire event.

### PR DESCRIPTION
**Pull request by JennDahm**
The stock hiring mechanism fires the OnCrewmemberHire event whenever a new kerbal is hired. This pull request would put that behavior into your replacement hiring service.

I also condensed the code that creates a new kerbal so that it is cleaner and better extendable.

### CODE REVIEW

**Comment by JennDahm** [comment]
Did moving the event fires to before the funding deduction really make that big a difference? It seemed to be working fine for me. (see 3bc6c5e369d555ac8d058d80f5698441cf6dfe88)

**Comment by OakTree42** [comment]
I didn't move it, I left it where it was in my earlier code? I had made an error in my copying your code in, which is why there was a problem before. It had nothing to do with your code it was my attempt to patch it in.
I did formally note your help in the readme file if you look? 
I don't think it matters either way, from what I can see... is there an issue in leaving it where it had been? Let me know if there is.
-OakTree42

**Comment by OakTree42** [comment]
I should note that all this updating and fumbling around with the various formats versions and the like I make mistakes all over the place. I'm not a coder by nature, this is something I worked on rather hard and did a lot of trial and error. If I some how did something wrong in how I updated things or incorporated your changes, which did streamline the code! Let me know? I am not trying to offend you and appreciate your help there.

**Comment by JennDahm** [comment]
You did, in fact, move those two calls up a few lines; at least, compared to my submitted code. It's really not a big deal, I don't think, though you should check whether the stock game deducts payment before or after firing the OnHire event. I would guess before, but I haven't actually tested.

I was just surprised that you closed the pull request and made virtually the same changes yourself, rather than merging my pull request and then adding some edits. A little bit about GitHub etiquette, since you're new to programming: when someone makes changes to your code and submits a pull request, you generally either reject the changes and explain why, or you work with them to refine the changes to a point you can mutually agree upon and then accept the pull request. This way, the submitter's work is catalogued in the commit log in addition to wherever else you'd like to credit them.

I've made the same mistake before when I was new. You did credit me in both the README and the commit itself, so I'm not unhappy or offended, but keep that tip in mind in the future. Good luck going forward! :)

PS concerning patching: you don't have to do it manually. You can always go to my fork and clone the repository to test the changes. That will save you a lot of frustration.

**Comment by OakTree42** [comment]
Trying to figure out how to accept this post what I did. Gah, I hate trying to learn new things like github and kerbalstuff. Why is this so much harder than simple C#??

**Comment by OakTree42** [comment]
I'm trying to make this right. I reopened your request but now I am getting something about not letting me merge (Probably because I already made changes?) And needing to do it by command line. It ever so helpfully says click on a spot for help with that but no help is provided. Sorry I'm bumbling around this, I am trying to do it right and I am sorry if I've messed this up. 
Also another issue I've run into is if I even alter a single thing here then I have to modify the version number and do it all over again to post it to kerbal stuff, which is annoying me no end. _sigh_ Anyway, just letting you know this is why it is reopend and I'm trying to fix it now.

**Comment by JennDahm** [comment]
Don't worry about it, dude. You already made the changes and you credited me just fine. You'd have to revert and then reapply a few commits to merge this pull request, and I don't think that's worth your time considering the changes have already been made.

And yes, version control can be a fickle thing. It's always difficult the first time you pick it up. :P

**Comment by OakTree42** [comment]
Thanks for understanding. I just want to do what's right by you and everyone that's helped me. 
Believe me, I'll try to do better in the future. While I have taken a class in C# learning how to use github or things like it was definitely NOT covered. Ah well. Anyway, thank you for being understanding.

**Comment by JennDahm** [comment]
You'll find that there's a lot of important things not covered in your CS classes. :P Good luck with everything! :)

**Pull request closed without merging**
